name: Continuous integration

on:
  push:
    branches:
      - master
  pull_request:
  merge_group:

env:
  RUSTFLAGS: -Dwarnings
  CARGO_INCREMENTAL: 0 # Speeds up the build (no cache) and reduces disk space!

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v4
    - name: Running rustfmt
      run: cargo fmt --all --check

  check-clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v4
    - name: Running clippy
      run: cargo clippy --all --all-targets

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v4
    - name: Running tests
      run: cargo test --all --no-fail-fast
